// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv.proto

#include "kv.pb.h"
#include "kv.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace kv {

static const char* KVService_method_names[] = {
  "/kv.KVService/Put",
  "/kv.KVService/Get",
};

std::unique_ptr< KVService::Stub> KVService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KVService::Stub> stub(new KVService::Stub(channel, options));
  return stub;
}

KVService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Put_(KVService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(KVService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KVService::Stub::Put(::grpc::ClientContext* context, const ::kv::PutRequest& request, ::kv::PutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kv::PutRequest, ::kv::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Put_, context, request, response);
}

void KVService::Stub::async::Put(::grpc::ClientContext* context, const ::kv::PutRequest* request, ::kv::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kv::PutRequest, ::kv::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void KVService::Stub::async::Put(::grpc::ClientContext* context, const ::kv::PutRequest* request, ::kv::PutResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kv::PutResponse>* KVService::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::kv::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kv::PutResponse, ::kv::PutRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Put_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kv::PutResponse>* KVService::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::kv::PutRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KVService::Stub::Get(::grpc::ClientContext* context, const ::kv::GetRequest& request, ::kv::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kv::GetRequest, ::kv::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void KVService::Stub::async::Get(::grpc::ClientContext* context, const ::kv::GetRequest* request, ::kv::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kv::GetRequest, ::kv::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KVService::Stub::async::Get(::grpc::ClientContext* context, const ::kv::GetRequest* request, ::kv::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kv::GetResponse>* KVService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kv::GetResponse, ::kv::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kv::GetResponse>* KVService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

KVService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVService::Service, ::kv::PutRequest, ::kv::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kv::PutRequest* req,
             ::kv::PutResponse* resp) {
               return service->Put(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVService::Service, ::kv::GetRequest, ::kv::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kv::GetRequest* req,
             ::kv::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
}

KVService::Service::~Service() {
}

::grpc::Status KVService::Service::Put(::grpc::ServerContext* context, const ::kv::PutRequest* request, ::kv::PutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVService::Service::Get(::grpc::ServerContext* context, const ::kv::GetRequest* request, ::kv::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ReplicationService_method_names[] = {
  "/kv.ReplicationService/Replicate",
};

std::unique_ptr< ReplicationService::Stub> ReplicationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ReplicationService::Stub> stub(new ReplicationService::Stub(channel, options));
  return stub;
}

ReplicationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Replicate_(ReplicationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ReplicationService::Stub::Replicate(::grpc::ClientContext* context, const ::kv::ReplicationPacket& request, ::kv::ReplicationAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kv::ReplicationPacket, ::kv::ReplicationAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Replicate_, context, request, response);
}

void ReplicationService::Stub::async::Replicate(::grpc::ClientContext* context, const ::kv::ReplicationPacket* request, ::kv::ReplicationAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kv::ReplicationPacket, ::kv::ReplicationAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Replicate_, context, request, response, std::move(f));
}

void ReplicationService::Stub::async::Replicate(::grpc::ClientContext* context, const ::kv::ReplicationPacket* request, ::kv::ReplicationAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Replicate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kv::ReplicationAck>* ReplicationService::Stub::PrepareAsyncReplicateRaw(::grpc::ClientContext* context, const ::kv::ReplicationPacket& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kv::ReplicationAck, ::kv::ReplicationPacket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Replicate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kv::ReplicationAck>* ReplicationService::Stub::AsyncReplicateRaw(::grpc::ClientContext* context, const ::kv::ReplicationPacket& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplicateRaw(context, request, cq);
  result->StartCall();
  return result;
}

ReplicationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReplicationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReplicationService::Service, ::kv::ReplicationPacket, ::kv::ReplicationAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReplicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kv::ReplicationPacket* req,
             ::kv::ReplicationAck* resp) {
               return service->Replicate(ctx, req, resp);
             }, this)));
}

ReplicationService::Service::~Service() {
}

::grpc::Status ReplicationService::Service::Replicate(::grpc::ServerContext* context, const ::kv::ReplicationPacket* request, ::kv::ReplicationAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kv
#include <grpcpp/ports_undef.inc>

